# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import file_service_pb2 as file__service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in file_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileServiceStub(object):
    """File transfer and node management service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/fileservice.FileService/RegisterNode',
                request_serializer=file__service__pb2.RegisterNodeRequest.SerializeToString,
                response_deserializer=file__service__pb2.RegisterNodeResponse.FromString,
                _registered_method=True)
        self.SendHeartbeat = channel.unary_unary(
                '/fileservice.FileService/SendHeartbeat',
                request_serializer=file__service__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=file__service__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.UnregisterNode = channel.unary_unary(
                '/fileservice.FileService/UnregisterNode',
                request_serializer=file__service__pb2.UnregisterNodeRequest.SerializeToString,
                response_deserializer=file__service__pb2.UnregisterNodeResponse.FromString,
                _registered_method=True)
        self.GetNodeStatus = channel.unary_unary(
                '/fileservice.FileService/GetNodeStatus',
                request_serializer=file__service__pb2.NodeStatusRequest.SerializeToString,
                response_deserializer=file__service__pb2.NodeStatusResponse.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/fileservice.FileService/ListFiles',
                request_serializer=file__service__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=file__service__pb2.ListFilesResponse.FromString,
                _registered_method=True)
        self.GetFileInfo = channel.unary_unary(
                '/fileservice.FileService/GetFileInfo',
                request_serializer=file__service__pb2.FileInfoRequest.SerializeToString,
                response_deserializer=file__service__pb2.FileInfoResponse.FromString,
                _registered_method=True)
        self.UploadFile = channel.stream_unary(
                '/fileservice.FileService/UploadFile',
                request_serializer=file__service__pb2.UploadChunkRequest.SerializeToString,
                response_deserializer=file__service__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.DownloadFile = channel.unary_stream(
                '/fileservice.FileService/DownloadFile',
                request_serializer=file__service__pb2.DownloadRequest.SerializeToString,
                response_deserializer=file__service__pb2.DownloadChunkResponse.FromString,
                _registered_method=True)
        self.TransferChunk = channel.unary_unary(
                '/fileservice.FileService/TransferChunk',
                request_serializer=file__service__pb2.TransferChunkRequest.SerializeToString,
                response_deserializer=file__service__pb2.TransferChunkResponse.FromString,
                _registered_method=True)
        self.RequestChunk = channel.unary_unary(
                '/fileservice.FileService/RequestChunk',
                request_serializer=file__service__pb2.ChunkRequest.SerializeToString,
                response_deserializer=file__service__pb2.ChunkResponse.FromString,
                _registered_method=True)


class FileServiceServicer(object):
    """File transfer and node management service
    """

    def RegisterNode(self, request, context):
        """Node management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """File operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferChunk(self, request, context):
        """Node-to-node file transfer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=file__service__pb2.RegisterNodeRequest.FromString,
                    response_serializer=file__service__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=file__service__pb2.HeartbeatRequest.FromString,
                    response_serializer=file__service__pb2.HeartbeatResponse.SerializeToString,
            ),
            'UnregisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterNode,
                    request_deserializer=file__service__pb2.UnregisterNodeRequest.FromString,
                    response_serializer=file__service__pb2.UnregisterNodeResponse.SerializeToString,
            ),
            'GetNodeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeStatus,
                    request_deserializer=file__service__pb2.NodeStatusRequest.FromString,
                    response_serializer=file__service__pb2.NodeStatusResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=file__service__pb2.ListFilesRequest.FromString,
                    response_serializer=file__service__pb2.ListFilesResponse.SerializeToString,
            ),
            'GetFileInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileInfo,
                    request_deserializer=file__service__pb2.FileInfoRequest.FromString,
                    response_serializer=file__service__pb2.FileInfoResponse.SerializeToString,
            ),
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=file__service__pb2.UploadChunkRequest.FromString,
                    response_serializer=file__service__pb2.UploadResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=file__service__pb2.DownloadRequest.FromString,
                    response_serializer=file__service__pb2.DownloadChunkResponse.SerializeToString,
            ),
            'TransferChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferChunk,
                    request_deserializer=file__service__pb2.TransferChunkRequest.FromString,
                    response_serializer=file__service__pb2.TransferChunkResponse.SerializeToString,
            ),
            'RequestChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestChunk,
                    request_deserializer=file__service__pb2.ChunkRequest.FromString,
                    response_serializer=file__service__pb2.ChunkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fileservice.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fileservice.FileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """File transfer and node management service
    """

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileservice.FileService/RegisterNode',
            file__service__pb2.RegisterNodeRequest.SerializeToString,
            file__service__pb2.RegisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileservice.FileService/SendHeartbeat',
            file__service__pb2.HeartbeatRequest.SerializeToString,
            file__service__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileservice.FileService/UnregisterNode',
            file__service__pb2.UnregisterNodeRequest.SerializeToString,
            file__service__pb2.UnregisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileservice.FileService/GetNodeStatus',
            file__service__pb2.NodeStatusRequest.SerializeToString,
            file__service__pb2.NodeStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileservice.FileService/ListFiles',
            file__service__pb2.ListFilesRequest.SerializeToString,
            file__service__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFileInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileservice.FileService/GetFileInfo',
            file__service__pb2.FileInfoRequest.SerializeToString,
            file__service__pb2.FileInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/fileservice.FileService/UploadFile',
            file__service__pb2.UploadChunkRequest.SerializeToString,
            file__service__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fileservice.FileService/DownloadFile',
            file__service__pb2.DownloadRequest.SerializeToString,
            file__service__pb2.DownloadChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileservice.FileService/TransferChunk',
            file__service__pb2.TransferChunkRequest.SerializeToString,
            file__service__pb2.TransferChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileservice.FileService/RequestChunk',
            file__service__pb2.ChunkRequest.SerializeToString,
            file__service__pb2.ChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
